version: 2
services:
  - type: web
    name: realtime-tracker-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
    autoDeploy: false
