version: 2
services:
  - type: web
    name: realtime-tracker-backend
    env: node
    plan: free
    buildCommand: npm install --production
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /api/health
